# Site settings
title: Fiziker
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A blog by a high energy physics graduate student.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://davidsheffield.github.io" # the base hostname & protocol for your site
twitter_username: Fiziker
#github_username:  jekyll

# Build settings
markdown: kramdown
