# Site settings
title: Fiziker
email: david@fiziker.com
description: > # this means to ignore newlines until "baseurl:"
  A blog by a high energy physics graduate student.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://fiziker.com" # the base hostname & protocol for your site
twitter_username: Fiziker
github_username:  davidsheffield

# Build settings
markdown: kramdown
